#!/bin/sh
set -eux


LIBMNL_VERSION=$(
  curl --location --show-error --silent \
  "https://www.netfilter.org/news.html" \
    | grep libmnl \
    | grep --extended-regexp --only-matching \
      '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+' \
    | head --lines 1
)
echo "${LIBMNL_VERSION}"

NGTCP2_VERSION="$( \
  curl --location --show-error --silent \
    https://github.com/ngtcp2/ngtcp2/releases.atom \
  | grep releases \
  | grep --extended-regexp --only-matching \
    '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+' \
  | head --lines 1
)"
echo "${NGTCP2_VERSION}"

OPENSSL_VERSION="$( \
  curl --location --show-error --silent \
    https://github.com/openssl/openssl/releases.atom \
  | grep --extended-regexp --only-matching \
    '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+' \
  | sort --numeric-sort --reverse \
  | head --lines 1
)"
echo "${OPENSSL_VERSION}"

UNBOUND_VERSION="$( \
  curl --location --show-error --silent \
  "https://github.com/NLnetLabs/unbound/releases.atom" \
  | grep --extended-regexp --only-matching \
    '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+' \
  | head --lines 1
)"
echo "${UNBOUND_VERSION}"


cat <<EOF > "${BUILD_FOLDER}"/build-arg.env
## generated by build-helper.sh

LIBMNL_VERSION=${LIBMNL_VERSION}
NGTCP2_VERSION=${NGTCP2_VERSION}
OPENSSL_VERSION=${OPENSSL_VERSION}
UNBOUND_VERSION=${UNBOUND_VERSION}
EOF

IMAGE_VERSION="${UNBOUND_VERSION}"
PLATFORM=linux/amd64,linux/arm/v7,linux/arm64/v8